_BASE_: "Base-BlendMask.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (40000, 1672050, 1672200)
  MAX_ITER: 2500000
OUTPUT_DIR: "output/blendmask/R_50_3x"
